= Cheatsheets

[[RedisOptions]]
== RedisOptions

++++
 Redis Client Configuration options.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[connectionString]]`@connectionString`|`String`|+++
Sets a single connection string (endpoint) to use while connecting to the redis server.
 Will replace the previously configured connection strings.
 <p>
 Does not support rediss (redis over ssl scheme) for now.
+++
|[[connectionStrings]]`@connectionStrings`|`Array of String`|+++
Adds a connection string (endpoint) to use while connecting to the redis server. Only the cluster mode will
 consider more than 1 element. If more are provided, they are not considered by the client when in single server mode.
 <p>
 Does not support rediss (redis over ssl scheme) for now.
+++
|[[endpoint]]`@endpoint`|`String`|+++
Sets a single connection string to use while connecting to the redis server.
 Will replace the previously configured connection strings.
+++
|[[endpoints]]`@endpoints`|`Array of String`|+++
Set the endpoints to use while connecting to the redis server. Only the cluster mode will consider more than
 1 element. If more are provided, they are not considered by the client when in single server mode.
+++
|[[masterName]]`@masterName`|`String`|+++
Set the master name (only considered in HA mode).
+++
|[[maxNestedArrays]]`@maxNestedArrays`|`Number (int)`|+++
Tune how much nested arrays are allowed on a redis response. This affects the parser performance.
+++
|[[maxPoolSize]]`@maxPoolSize`|`Number (int)`|+++
Tune the maximum size of the connection pool. When working with cluster or sentinel
 this value should be atleast the total number of cluster member (or number of sentinels + 1)
+++
|[[maxPoolWaiting]]`@maxPoolWaiting`|`Number (int)`|+++
Tune the maximum waiting requests for a connection from the pool.
+++
|[[maxWaitingHandlers]]`@maxWaitingHandlers`|`Number (int)`|+++
The client will always work on pipeline mode, this means that messages can start queueing. You can control how much
 backlog you're willing to accept. This methods sets how much handlers is the client willing to queue.
+++
|[[netClientOptions]]`@netClientOptions`|`link:dataobjects.html#NetClientOptions[NetClientOptions]`|+++
Set the net client options to be used while connecting to the redis server. Use this to tune your connection.
+++
|[[poolCleanerInterval]]`@poolCleanerInterval`|`Number (int)`|+++
Tune how often in milliseconds should the connection pool cleaner execute.
+++
|[[poolRecycleTimeout]]`@poolRecycleTimeout`|`Number (int)`|+++
Tune when a connection should be recycled in milliseconds.
+++
|[[role]]`@role`|`link:enums.html#RedisRole[RedisRole]`|+++
Set the role name (only considered in HA mode).
+++
|[[type]]`@type`|`link:enums.html#RedisClientType[RedisClientType]`|+++
Set the desired client type to be created.
+++
|[[useSlave]]`@useSlave`|`link:enums.html#RedisSlaves[RedisSlaves]`|+++
Set whether or not to use slave nodes (only considered in Cluster mode).
+++
|===

