= Cheatsheets

[[KillFilter]]
== KillFilter

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[addr]]`addr`|`String`|
+++
Set ADDR filter
+++
|[[id]]`id`|`String`|
+++
Set ID filter
+++
|[[skipme]]`skipme`|`Boolean`|
+++
Set SKIPME filter
+++
|[[type]]`type`|`link:enums.html#Type[Type]`|
+++
Set TYPE filter
+++
|===

[[LimitOptions]]
== LimitOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[SortOptions]]
== SortOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[by]]`by`|`String`|-
|[[gets]]`gets`|`Array of String`|-
|[[store]]`store`|`String`|-
|===

[[SetOptions]]
== SetOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[ex]]`ex`|`Number (long)`|-
|[[nx]]`nx`|`Boolean`|-
|[[px]]`px`|`Number (long)`|-
|[[xx]]`xx`|`Boolean`|-
|===

[[MigrateOptions]]
== MigrateOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

[[ScanOptions]]
== ScanOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[count]]`count`|`Number (int)`|-
|[[match]]`match`|`String`|-
|===

[[RedisOptions]]
== RedisOptions

++++
 This object controls the connection setting to the Redis Server. There is no need to specify most of the settings
 since it has built the following sensible defaults:

 * `encoding`: `UTF-8`
 * `host`: `localhost`
 * `port`: 6379
 * `tcpKeepAlive`: true
 * `tcpNoDelay`: true

 However there are two extra properties that have no defaults since they are optional:

 * `auth`
 * `select`

 The usage of this two extra properties is to setup required authentication and optionally the selection of the active
 database at connection time. If you define this extra properties on every connection to Redis server this client
 will perform the authentication handshake and database selection, however if you don't do this and call link
 yourself in case of connection failure the client will not be able to perform the correct authentication handshake.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Set the eventbus address prefix for `PUB/SUB`.
+++
|[[auth]]`auth`|`String`|
+++
Set the password for authentication at connection time.
+++
|[[encoding]]`encoding`|`String`|
+++
Set the user defined character encoding, e.g.: `iso-8859-1`.
+++
|[[host]]`host`|`String`|
+++
Set the host name where the Redis server is listening.
+++
|[[port]]`port`|`Number (int)`|
+++
Set the tcp port where the Redis server is listening.
+++
|[[select]]`select`|`Number (Integer)`|
+++
Set the database to select at connection time.
+++
|[[tcpKeepAlive]]`tcpKeepAlive`|`Boolean`|
+++
Set the TCP KeepAlive option
+++
|[[tcpNoDelay]]`tcpNoDelay`|`Boolean`|
+++
Set the TCP NoDelay at the socket level.
+++
|===

[[RangeLimitOptions]]
== RangeLimitOptions

++++
 @author <a href="mailto:marko.strukelj@gmail.com">Marko Strukelj</a>
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|===

