= Enums

[[RedisClientType]]
== RedisClientType

++++
 Define what kind of behavior is expected from the client.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[STANDALONE]]`STANDALONE`|+++
The client should work in single server mode (the default).
+++
|[[SENTINEL]]`SENTINEL`|+++
The client should work in sentinel mode. When this mode is active
 use the link to define which role to get the client
 connection to.
+++
|[[CLUSTER]]`CLUSTER`|+++
The client should work in cluster mode. When this mode is active
 use the link to define when replica nodes can be
 used for read only queries.
+++
|===

[[RedisReplicas]]
== RedisReplicas

++++
 When should Redis replica nodes be used for queries.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NEVER]]`NEVER`|+++
Never use REPLICA, queries are always run on a MASTER node.
+++
|[[SHARE]]`SHARE`|+++
Queries can be randomly run on both MASTER and REPLICA nodes.
+++
|[[ALWAYS]]`ALWAYS`|+++
Queries are always run on REPLICA nodes (never on MASTER node).
+++
|===

[[RedisRole]]
== RedisRole

++++
 Define which kind of role to be used in HA mode.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[MASTER]]`MASTER`|+++
Use a MASTER node connection.
+++
|[[SLAVE]]`SLAVE`|+++
Use a SLAVE node connection.
+++
|[[SENTINEL]]`SENTINEL`|+++
Use a SENTINEL node connection.
+++
|===

[[ResponseType]]
== ResponseType

++++
 Define the response types that the client can receive from REDIS.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SIMPLE]]`SIMPLE`|+++
C String simple String.
+++
|[[ERROR]]`ERROR`|+++
C String simple String representing an error.
+++
|[[BOOLEAN]]`BOOLEAN`|+++
boolean value.
+++
|[[NUMBER]]`NUMBER`|+++
numeric value.
+++
|[[BULK]]`BULK`|+++
byte array value.
+++
|[[PUSH]]`PUSH`|+++
Push message
+++
|[[ATTRIBUTE]]`ATTRIBUTE`|+++
Attribute message
+++
|[[MULTI]]`MULTI`|+++
List of multiple bulk responses (List, Set, Map).
+++
|===

