= Enums

[[RedisClientType]]
== RedisClientType

++++
 Define what kind of behavior is expected from the client.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[STANDALONE]]`STANDALONE`|+++
The client should work in single server mode (the default).
+++
|[[SENTINEL]]`SENTINEL`|+++
The client should work in sentinel mode. When this mode is active
 use the link to define which role to get the client
 connection to.
+++
|[[CLUSTER]]`CLUSTER`|+++
The client should work in cluster mode. When this mode is active
 use the link to define when slave nodes can be used
 for read only queries.
+++
|===

[[RedisRole]]
== RedisRole

++++
 Define which kind of role to be used in HA mode.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[MASTER]]`MASTER`|+++
Use a MASTER node connection.
+++
|[[SLAVE]]`SLAVE`|+++
Use a SLAVE node connection.
+++
|[[SENTINEL]]`SENTINEL`|+++
Use a SENTINEL node connection.
+++
|===

[[RedisSlaves]]
== RedisSlaves

++++
 When should Redis Slave nodes be used for queries.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[NEVER]]`NEVER`|+++
Never use SLAVES, queries are always run on a MASTER node.
+++
|[[SHARE]]`SHARE`|+++
Queries can be randomly run on both MASTER and SLAVE nodes.
+++
|[[ALWAYS]]`ALWAYS`|+++
Queries are always run on SLAVE nodes (never on MASTER node).
+++
|===

[[ResponseType]]
== ResponseType

++++
 Define the response types that the client can receive from REDIS.
++++
'''

[cols=">25%,75%"]
[frame="topbot"]
|===
^|Name | Description
|[[SIMPLE]]`SIMPLE`|+++
C String simple String.
+++
|[[ERROR]]`ERROR`|+++
C String simple String representing an error.
+++
|[[INTEGER]]`INTEGER`|+++
64 bit integer value.
+++
|[[BULK]]`BULK`|+++
byte array value.
+++
|[[MULTI]]`MULTI`|+++
List of multiple bulk responses.
+++
|===

